[target.aarch64-unknown-linux-gnu]
linker = "/home/ubuntu/build-toolchain/arm/aarch64/arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-gcc"
ar = "/home/ubuntu/build-toolchain/arm/aarch64/arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-ar"
