[target.aarch64-unknown-linux-gnu]
linker = "E:\\Build_Toolchain\\arm\\aarch64\\arm-gnu-toolchain-12.3.rel1-mingw-w64-i686-aarch64-none-linux-gnu\\bin\\aarch64-none-linux-gnu-gcc.exe"
ar = "E:\\Build_Toolchain\\arm\\aarch64\\arm-gnu-toolchain-12.3.rel1-mingw-w64-i686-aarch64-none-linux-gnu\\bin\\aarch64-none-linux-gnu-ar.exe"
